// src/services/api.constant.ts
export const apiConst = Object.freeze({
  webLogin: "Login/LoginO",
  sendOtp: "SendOtp",
  loginWithOtp: "loginWithOtp",
  tokenSetup: "tokenSetup",
  getIdByUserToken: "user/GetByToken",
  getAllConfiguration: "Setting/GetAll",
  insertConfiguration: "Setting/Insert",
  updateConfiguration: "Setting/Update",
  deleteConfiguration: "Setting/Delete",
  getAllProgramTemplate: "ProgramTemplate/GetAll",
  getAllDefaultRibbons: "Menu/GetAll",
  // EntityType جداول مختلف (LessonLearnedFormTemplate, CommentFormTemplate, ProcedureFormTemplate)
  getTableTransmittal: "EntityType/GetAllComplete",
  // LessonLearnedAfTemplate
  getAllWfTemplate: "WFTemplate/GetAll",
  getAllAfbtn: "AFBtn/GetAll",
  insertAFBtn: "AFBtn/Insert",
  updateAFBtn: "AFBtn/Update",
  deleteAFBtn: "AFBtn/Delete",
  uploadFile: "File/Upload",
  insert: "File/Insert",
  download: "File/Download",
  getFile: "File/GetById",
  getCommand: "Command/GetAll",
  insertCommand: "Command/Insert",
  deleteCommand: "Command/Delete",
  updateCommand: "Command/Update",
  getEnum: "GetEnumByName",
  getAllMenu: "Menu/GetAll",
  insertMenu: "Menu/Insert",
  updateMenu: "Menu/Update",
  deleteMenu: "Menu/Delete",
  getAllMenuTab: "MenuTab/GetByMenuId",
  insertMenuTab: "MenuTab/Insert",
  updateMenuTab: "MenuTab/Update",
  deleteMenuTab: "MenuTab/Delete",
  getAllMenuGroup: "MenuGroup/GetAllByMenuTabID",
  insertMenuGroup: "MenuGroup/Insert",
  updateMenuGroup: "MenuGroup/Update",
  deleteMenuGroup: "MenuGroup/Delete",
  getAllMenuItem: "MenuItem/GetAllByMenuGroupId",
  insertMenuItem: "MenuItem/Insert",
  updateMenuItem: "MenuItem/Update",
  deleteMenuItem: "MenuItem/Delete",
});

// getAllMenuTab: "MenuTab/GetByMenuId",
// getAllMenuGroup: "MenuGroup/GetAllByMenuGroupId",
// getAllMenuItem: "MenuItem/GetAllByMenuTabID",

export const apiConstClient = Object.freeze({
  GetAllMenuClient: "Menu/GetAllForClient",
  GetZipFullMenuClient: "Menu/GetZipFullMenuClient",
});
